using Content.Client.Computer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

using Content.Client.Resources;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;

using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.ClockCult.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ThingWindow : DefaultWindow
    {

        private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

        private int xpos = 0;
        private int ypos = 0;

        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;

        public ThingWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            XPositionEdit.OnTextChanged += OnValueChanged;
            YPositionEdit.OnTextChanged += OnValueChanged;
            UpdateButton.OnPressed += OnUpdatePress;

            var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
            var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

            CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
            CameraViewBackground.Texture = texture;
            CameraViewBackground.ShaderOverride = shader;
        }

        private void OnValueChanged(LineEdit.LineEditEventArgs args)
        {
            if (int.TryParse(XPositionEdit.Text, out var xAmount) && int.TryParse(YPositionEdit.Text, out var yAmount))
            {
               UpdateButton.Text = ("Observe (" + XPositionEdit.Text + ", " + YPositionEdit.Text + ")");
               xpos = xAmount;
               ypos = yAmount;
            }
        }

        private void OnUpdatePress(BaseButton.ButtonEventArgs args)
        {
            TeleportButton.Text = ("Teleport to (" + xpos.ToString() + ", " + ypos.ToString() + ")");
        }
    }
}
